import { Medicine, Pharmacy, InventoryItem, Reminder } from '../types';

export const INITIAL_MEDICINES: Medicine[] = [
  {
    id: 'med-1',
    name: 'Paracetamol 500mg',
    generic_name: 'Acetaminophen / Paracetamol',
    manufacturer: 'GSK Pharmaceuticals Ltd.',
    strength: '500 mg',
    form: 'Tablet',
    category: 'Analgesics & Antipyretics',
    description: 'Paracetamol is a widely used over-the-counter pain reliever and fever reducer. It works by blocking chemical messengers in the brain that tell us we have pain and regulates body temperature.',
    uses: ['Mild to moderate headaches', 'Fever and body aches', 'Post-immunization pyrexia', 'Muscle aches & toothaches'],
    side_effects: ['Rare when taken in normal doses', 'Nausea (occasional)', 'Liver strain if excessive dose (>4000mg/day)'],
    precautions: ['Do not exceed 4g in 24 hours', 'Avoid concurrent alcohol consumption', 'Consult doctor if liver or kidney impaired'],
    dosage_info: 'Adults: 1-2 tablets (500mg - 1000mg) every 4-6 hours as needed. Max 4000mg per 24 hours.',
    prescription_required: false,
    average_price: 3.50,
    available_pharmacies_count: 5,
    stock_status: 'available'
  },
  {
    id: 'med-2',
    name: 'Cetirizine 10mg',
    generic_name: 'Cetirizine Hydrochloride',
    manufacturer: 'Dr. Reddy\'s Laboratories',
    strength: '10 mg',
    form: 'Tablet',
    category: 'Antihistamines',
    description: 'Second-generation antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, sneezing, hives, and itching.',
    uses: ['Allergic rhinitis & hay fever', 'Chronic urticaria (hives)', 'Allergic conjunctivitis', 'Skin allergies'],
    side_effects: ['Mild drowsiness', 'Dry mouth', 'Fatigue', 'Dizziness'],
    precautions: ['May cause mild sedation; caution while driving', 'Reduce dosage in severe renal impairment', 'Avoid alcohol'],
    dosage_info: 'Adults and children over 12: 10mg once daily in the evening.',
    prescription_required: false,
    average_price: 4.20,
    available_pharmacies_count: 4,
    stock_status: 'available'
  },
  {
    id: 'med-3',
    name: 'Azithromycin 500mg',
    generic_name: 'Azithromycin',
    manufacturer: 'Pfizer Inc.',
    strength: '500 mg',
    form: 'Tablet',
    category: 'Antibiotics (Macrolide)',
    description: 'Macrolide-type antibiotic that fights bacteria. It is used to treat various bacterial infections of the respiratory tract, ear, skin, and certain sexually transmitted infections.',
    uses: ['Bacterial sinusitis & pharyngitis', 'Community-acquired pneumonia', 'Skin & soft tissue infections', 'Tonsillitis'],
    side_effects: ['Diarrhea / loose stools', 'Abdominal cramps', 'Nausea / vomiting', 'Headache'],
    precautions: ['Complete full prescribed course', 'Do not take with aluminum/magnesium antacids simultaneously', 'Report severe palpitations'],
    dosage_info: 'Usually 500mg once daily for 3 to 5 days as prescribed by physician.',
    prescription_required: true,
    average_price: 12.80,
    available_pharmacies_count: 4,
    stock_status: 'available'
  },
  {
    id: 'med-4',
    name: 'Amoxicillin + Clavulanic Acid 625mg',
    generic_name: 'Amoxicillin and Potassium Clavulanate (Augmentin)',
    manufacturer: 'GlaxoSmithKline',
    strength: '625 mg (500mg/125mg)',
    form: 'Tablet',
    category: 'Antibiotics (Penicillin)',
    description: 'Broad-spectrum antibacterial combination consisting of amoxicillin and clavulanic acid, which inhibits beta-lactamase enzymes produced by resistant bacteria.',
    uses: ['Ear, nose and throat infections', 'Lower respiratory tract infections', 'Urinary tract infections', 'Dental abscesses'],
    side_effects: ['Diarrhea', 'Nausea', 'Skin rash / fungal superinfections'],
    precautions: ['Contraindicated in penicillin allergy', 'Take with food to minimize gastrointestinal discomfort'],
    dosage_info: 'One 625mg tablet twice daily or three times daily as directed by doctor.',
    prescription_required: true,
    average_price: 14.50,
    available_pharmacies_count: 3,
    stock_status: 'low_stock'
  },
  {
    id: 'med-5',
    name: 'Metformin 500mg SR',
    generic_name: 'Metformin Hydrochloride (Sustained Release)',
    manufacturer: 'Sun Pharma',
    strength: '500 mg',
    form: 'Tablet',
    category: 'Antidiabetic (Biguanide)',
    description: 'First-line medication for the treatment of type 2 diabetes mellitus, particularly in people who are overweight. It helps lower blood glucose levels.',
    uses: ['Type 2 Diabetes Mellitus glycemic control', 'Polycystic Ovary Syndrome (PCOS) insulin resistance'],
    side_effects: ['Gastrointestinal upset', 'Metallic taste in mouth', 'Nausea'],
    precautions: ['Take with or after meals to minimize stomach upset', 'Monitor renal function periodically', 'Risk of lactic acidosis with heavy alcohol'],
    dosage_info: 'Initial: 500mg once or twice daily with main meals. Titrated by doctor.',
    prescription_required: true,
    average_price: 5.10,
    available_pharmacies_count: 5,
    stock_status: 'available'
  },
  {
    id: 'med-6',
    name: 'Atorvastatin 20mg',
    generic_name: 'Atorvastatin Calcium',
    manufacturer: 'Zydus Cadila',
    strength: '20 mg',
    form: 'Tablet',
    category: 'Lipid-Lowering Agent (Statin)',
    description: 'HMG-CoA reductase inhibitor used to decrease low-density lipoprotein (LDL) cholesterol and triglycerides in blood while increasing HDL cholesterol.',
    uses: ['Hypercholesterolemia', 'Cardiovascular event prevention', 'Atherosclerosis management'],
    side_effects: ['Myalgia / muscle ache', 'Elevated liver enzymes', 'Digestive disturbance'],
    precautions: ['Report unexplained muscle tenderness immediately', 'Take once daily at night or same time every day', 'Avoid grapefruit juice in large quantities'],
    dosage_info: '10mg to 20mg once daily at bedtime or consistent hour.',
    prescription_required: true,
    average_price: 8.90,
    available_pharmacies_count: 4,
    stock_status: 'available'
  },
  {
    id: 'med-7',
    name: 'Pantoprazole 40mg',
    generic_name: 'Pantoprazole Sodium',
    manufacturer: 'Alkem Laboratories',
    strength: '40 mg',
    form: 'Tablet',
    category: 'Proton Pump Inhibitor (PPI)',
    description: 'Proton pump inhibitor that suppresses stomach acid secretion. Indicated for acidity, heartburn, gastroesophageal reflux disease (GERD), and peptic ulcers.',
    uses: ['Gastroesophageal reflux disease (GERD)', 'Gastric & duodenal ulcers', 'Zollinger-Ellison syndrome', 'NSAID-induced ulcer prevention'],
    side_effects: ['Headache', 'Flatulence', 'Mild diarrhea or constipation'],
    precautions: ['Take 30-60 minutes before breakfast on an empty stomach', 'Swallow whole, do not crush or chew'],
    dosage_info: 'One 40mg tablet once daily in the morning before meals.',
    prescription_required: false,
    average_price: 6.20,
    available_pharmacies_count: 5,
    stock_status: 'available'
  },
  {
    id: 'med-8',
    name: 'Salbutamol Inhaler 100mcg',
    generic_name: 'Salbutamol (Albuterol) Inhaler',
    manufacturer: 'Cipla Ltd.',
    strength: '100 mcg per actuation (200 doses)',
    form: 'Inhaler',
    category: 'Respiratory / Bronchodilator',
    description: 'Fast-acting beta-2 adrenergic agonist bronchodilator used for rapid relief of bronchospasm in asthma and chronic obstructive pulmonary disease (COPD).',
    uses: ['Acute asthma attack relief', 'Exercise-induced bronchospasm prevention', 'COPD symptom flare-ups'],
    side_effects: ['Mild tremors', 'Palpitations', 'Throat irritation'],
    precautions: ['Keep accessible at all times', 'Rinse mouth after use to prevent dryness', 'Seek urgent care if breathing does not improve after 2-4 puffs'],
    dosage_info: '1 to 2 puffs for acute symptoms. May repeat after 4 hours. Max 8 puffs/day without medical supervision.',
    prescription_required: true,
    average_price: 11.20,
    available_pharmacies_count: 2,
    stock_status: 'low_stock'
  },
  {
    id: 'med-9',
    name: 'Montelukast + Levocetirizine',
    generic_name: 'Montelukast 10mg + Levocetirizine 5mg',
    manufacturer: 'Lupin Pharma',
    strength: '10mg / 5mg',
    form: 'Tablet',
    category: 'Antiallergic & Leukotriene Antagonist',
    description: 'Dual combination targeting histaminic and leukotriene allergic pathways for effective control of persistent allergic asthma and severe rhinitis.',
    uses: ['Allergic rhinitis with asthma symptoms', 'Seasonal hay fever', 'Chronic perennial allergies'],
    side_effects: ['Drowsiness', 'Fatigue', 'Headache', 'Mild abdominal discomfort'],
    precautions: ['Take in evening with or without food', 'Report mood changes or sleep disturbances to doctor'],
    dosage_info: '1 tablet once daily in the evening.',
    prescription_required: true,
    average_price: 9.80,
    available_pharmacies_count: 3,
    stock_status: 'available'
  },
  {
    id: 'med-10',
    name: 'Ibuprofen 400mg',
    generic_name: 'Ibuprofen',
    manufacturer: 'Abbott Healthcare',
    strength: '400 mg',
    form: 'Tablet',
    category: 'NSAID (Non-steroidal Anti-inflammatory)',
    description: 'Non-steroidal anti-inflammatory drug (NSAID) used for reducing inflammation, relieving moderate pain, and lowering fever.',
    uses: ['Arthritis & joint pain', 'Menstrual cramps (dysmenorrhea)', 'Sprains and sports injuries', 'Dental pain'],
    side_effects: ['Gastric irritation / heartburn', 'Nausea', 'Fluid retention'],
    precautions: ['Always take with meals or milk', 'Avoid in active peptic ulcer disease or severe heart failure', 'Do not combine with other NSAIDs'],
    dosage_info: 'Adults: 400mg every 6 to 8 hours with food. Max 1200mg/day OTC.',
    prescription_required: false,
    average_price: 4.80,
    available_pharmacies_count: 4,
    stock_status: 'available'
  },
  {
    id: 'med-11',
    name: 'Amlodipine 5mg',
    generic_name: 'Amlodipine Besylate',
    manufacturer: 'Torrent Pharma',
    strength: '5 mg',
    form: 'Tablet',
    category: 'Antihypertensive (Calcium Channel Blocker)',
    description: 'Dihydropyridine calcium channel blocker used to treat high blood pressure (hypertension) and angina (chest pain).',
    uses: ['Essential hypertension', 'Chronic stable angina', 'Vasospastic angina'],
    side_effects: ['Peripheral edema (ankle swelling)', 'Flushing', 'Dizziness on standing'],
    precautions: ['Take regularly at same time daily', 'Do not abruptly discontinue', 'Monitor blood pressure regularly'],
    dosage_info: '5mg once daily, increased to 10mg if needed under medical advice.',
    prescription_required: true,
    average_price: 4.40,
    available_pharmacies_count: 5,
    stock_status: 'available'
  },
  {
    id: 'med-12',
    name: 'Losartan Potassium 50mg',
    generic_name: 'Losartan Potassium',
    manufacturer: 'Micro Labs Ltd.',
    strength: '50 mg',
    form: 'Tablet',
    category: 'Antihypertensive (ARB)',
    description: 'Angiotensin II receptor blocker that relaxes blood vessels to lower blood pressure and protect kidney function in diabetic patients.',
    uses: ['High blood pressure', 'Diabetic nephropathy in type 2 diabetes', 'Stroke risk reduction in hypertensive patients'],
    side_effects: ['Dizziness', 'Hyperkalemia (high potassium)', 'Fatigue'],
    precautions: ['Strictly contraindicated during pregnancy', 'Monitor serum potassium levels', 'Maintain adequate hydration'],
    dosage_info: '50mg once daily; can be increased to 100mg once daily.',
    prescription_required: true,
    average_price: 6.90,
    available_pharmacies_count: 0,
    stock_status: 'unavailable'
  },
  {
    id: 'med-13',
    name: 'Vitamin D3 60,000 IU',
    generic_name: 'Cholecalciferol',
    manufacturer: 'Cadila Healthcare',
    strength: '60,000 IU',
    form: 'Capsule',
    category: 'Nutritional / Vitamins',
    description: 'High-potency cholecalciferol formulation used to treat and prevent vitamin D deficiency, support bone density, and strengthen immune health.',
    uses: ['Vitamin D3 deficiency', 'Osteopenia / Osteoporosis adjunct', 'Bone and joint pain due to hypocalcemia'],
    side_effects: ['Rare at recommended therapeutic schedules', 'Constipation if excessive'],
    precautions: ['Take with milk or fatty meal for optimal absorption', 'Follow weekly schedule carefully; do not take daily'],
    dosage_info: 'Typically 1 capsule once weekly for 8 weeks, followed by monthly maintenance as prescribed.',
    prescription_required: false,
    average_price: 7.50,
    available_pharmacies_count: 5,
    stock_status: 'available'
  },
  {
    id: 'med-14',
    name: 'Ciprofloxacin 500mg',
    generic_name: 'Ciprofloxacin Hydrochloride',
    manufacturer: 'Bayer HealthCare',
    strength: '500 mg',
    form: 'Tablet',
    category: 'Antibiotics (Fluoroquinolone)',
    description: 'Fluoroquinolone antibiotic used to treat bacterial infections of the urinary tract, gastrointestinal tract, skin, and bones.',
    uses: ['Complicated urinary tract infections (UTIs)', 'Infectious diarrhea / gastroenteritis', 'Bone and joint infections'],
    side_effects: ['Nausea', 'Tendinitis risk', 'Dizziness', 'Photosensitivity'],
    precautions: ['Drink plenty of fluids', 'Avoid excessive sunlight exposure', 'Avoid simultaneous intake of antacids or iron supplements'],
    dosage_info: '500mg twice daily every 12 hours for 5-7 days as prescribed.',
    prescription_required: true,
    average_price: 11.50,
    available_pharmacies_count: 2,
    stock_status: 'low_stock'
  },
  {
    id: 'med-15',
    name: 'Omeprazole 20mg',
    generic_name: 'Omeprazole',
    manufacturer: 'AstraZeneca',
    strength: '20 mg',
    form: 'Capsule',
    category: 'Gastrointestinal (PPI)',
    description: 'Proton pump inhibitor that decreases the amount of acid produced in the stomach. Widely used for acid reflux, ulcers, and heartburn.',
    uses: ['Frequent heartburn (>2 days/week)', 'Gastroesophageal reflux', 'H. pylori eradication (with antibiotics)'],
    side_effects: ['Headache', 'Stomach ache', 'Mild diarrhea'],
    precautions: ['Take 30 mins before morning breakfast', 'Do not crush capsules'],
    dosage_info: '20mg once daily in the morning before food.',
    prescription_required: false,
    average_price: 5.70,
    available_pharmacies_count: 4,
    stock_status: 'available'
  },
  {
    id: 'med-16',
    name: 'Dolo 650',
    generic_name: 'Paracetamol 650mg',
    manufacturer: 'Micro Labs Ltd.',
    strength: '650 mg',
    form: 'Tablet',
    category: 'Analgesics & Antipyretics',
    description: 'High-strength paracetamol formulation specifically indicated for higher fever, body aches, viral fevers, and dental pain.',
    uses: ['High viral fever', 'Severe headache & flu aches', 'Post-vaccination fever'],
    side_effects: ['Extremely rare at normal doses', 'Mild nausea'],
    precautions: ['Maintain minimum 6-hour gap between doses', 'Do not exceed 4 tablets in 24 hours'],
    dosage_info: '1 tablet (650mg) every 6-8 hours as required. Max 3000mg/day.',
    prescription_required: false,
    average_price: 3.80,
    available_pharmacies_count: 5,
    stock_status: 'available'
  }
];

export const INITIAL_PHARMACIES: Pharmacy[] = [
  {
    id: 'pharm-1',
    name: 'Apollo 24|7 Pharmacy — Metro Heights',
    address: 'Shop 4-5, Ground Floor, Metro Heights, 100ft Ring Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560078',
    phone: '+91 80 2658 9100',
    email: 'metroheights@apollopharmacy.org',
    latitude: 12.9716,
    longitude: 77.5946,
    rating: 4.8,
    reviews_count: 320,
    opening_hours: '24 Hours Open',
    is_open_now: true,
    is_24x7: true,
    distance_km: 0.8
  },
  {
    id: 'pharm-2',
    name: 'MedPlus Health & Chemist',
    address: 'No. 42, 12th Main, 4th Block, Koramangala',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560034',
    phone: '+91 80 4123 5588',
    email: 'koramangala@medplusindia.com',
    latitude: 12.9352,
    longitude: 77.6245,
    rating: 4.6,
    reviews_count: 215,
    opening_hours: '7:30 AM – 11:00 PM',
    is_open_now: true,
    is_24x7: false,
    distance_km: 1.4
  },
  {
    id: 'pharm-3',
    name: 'Wellness Forever Day & Night Chemists',
    address: 'Plot 18, 80ft Road, Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560038',
    phone: '+91 80 2520 8899',
    email: 'indiranagar@wellnessforever.in',
    latitude: 12.9784,
    longitude: 77.6408,
    rating: 4.9,
    reviews_count: 480,
    opening_hours: '24 Hours Open',
    is_open_now: true,
    is_24x7: true,
    distance_km: 2.1
  },
  {
    id: 'pharm-4',
    name: 'Fortis Healthway Pharmacy',
    address: 'Fortis Hospital Campus, Bannerghatta Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560076',
    phone: '+91 80 6621 4444',
    email: 'healthway@fortishealthcare.com',
    latitude: 12.8984,
    longitude: 77.5997,
    rating: 4.7,
    reviews_count: 190,
    opening_hours: '8:00 AM – 10:30 PM',
    is_open_now: true,
    is_24x7: false,
    distance_km: 3.2
  },
  {
    id: 'pharm-5',
    name: 'Care & Cure Community Chemist',
    address: 'Shop 11, Green Glen Layout, Bellandur',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560103',
    phone: '+91 80 2574 1234',
    email: 'support@carecurechemist.com',
    latitude: 12.9260,
    longitude: 77.6762,
    rating: 4.4,
    reviews_count: 98,
    opening_hours: '8:00 AM – 10:00 PM',
    is_open_now: true,
    is_24x7: false,
    distance_km: 4.5
  },
  {
    id: 'pharm-6',
    name: 'Guardian Lifecare Pharmacy',
    address: 'Near Central Mall, Outer Ring Road, Marathahalli',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560037',
    phone: '+91 80 4099 7711',
    email: 'marathahalli@guardianlifecare.com',
    latitude: 12.9569,
    longitude: 77.7011,
    rating: 4.5,
    reviews_count: 140,
    opening_hours: '8:30 AM – 11:30 PM',
    is_open_now: true,
    is_24x7: false,
    distance_km: 5.1
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    pharmacy_id: 'pharm-1',
    medicine_id: 'med-1',
    pharmacy_name: 'Apollo 24|7 Pharmacy — Metro Heights',
    medicine_name: 'Paracetamol 500mg',
    generic_name: 'Acetaminophen / Paracetamol',
    strength: '500 mg',
    form: 'Tablet',
    stock_quantity: 140,
    price: 3.20,
    status: 'available',
    batch_number: 'PCM-2025-08',
    expiry_date: '2027-11-30',
    last_updated: '2026-08-10'
  },
  {
    id: 'inv-2',
    pharmacy_id: 'pharm-2',
    medicine_id: 'med-1',
    pharmacy_name: 'MedPlus Health & Chemist',
    medicine_name: 'Paracetamol 500mg',
    generic_name: 'Acetaminophen / Paracetamol',
    strength: '500 mg',
    form: 'Tablet',
    stock_quantity: 85,
    price: 3.50,
    status: 'available',
    batch_number: 'MED-7712',
    expiry_date: '2028-02-28',
    last_updated: '2026-08-12'
  },
  {
    id: 'inv-3',
    pharmacy_id: 'pharm-3',
    medicine_id: 'med-1',
    pharmacy_name: 'Wellness Forever Day & Night Chemists',
    medicine_name: 'Paracetamol 500mg',
    generic_name: 'Acetaminophen / Paracetamol',
    strength: '500 mg',
    form: 'Tablet',
    stock_quantity: 210,
    price: 3.40,
    status: 'available',
    batch_number: 'WF-PAR-90',
    expiry_date: '2027-09-15',
    last_updated: '2026-08-14'
  },
  {
    id: 'inv-4',
    pharmacy_id: 'pharm-1',
    medicine_id: 'med-2',
    pharmacy_name: 'Apollo 24|7 Pharmacy — Metro Heights',
    medicine_name: 'Cetirizine 10mg',
    generic_name: 'Cetirizine Hydrochloride',
    strength: '10 mg',
    form: 'Tablet',
    stock_quantity: 60,
    price: 4.10,
    status: 'available',
    batch_number: 'CTZ-4410',
    expiry_date: '2027-08-30',
    last_updated: '2026-08-11'
  },
  {
    id: 'inv-5',
    pharmacy_id: 'pharm-2',
    medicine_id: 'med-2',
    pharmacy_name: 'MedPlus Health & Chemist',
    medicine_name: 'Cetirizine 10mg',
    generic_name: 'Cetirizine Hydrochloride',
    strength: '10 mg',
    form: 'Tablet',
    stock_quantity: 45,
    price: 4.25,
    status: 'available',
    batch_number: 'MP-CTZ-09',
    expiry_date: '2027-10-15',
    last_updated: '2026-08-09'
  },
  {
    id: 'inv-6',
    pharmacy_id: 'pharm-1',
    medicine_id: 'med-3',
    pharmacy_name: 'Apollo 24|7 Pharmacy — Metro Heights',
    medicine_name: 'Azithromycin 500mg',
    generic_name: 'Azithromycin',
    strength: '500 mg',
    form: 'Tablet',
    stock_quantity: 32,
    price: 12.50,
    status: 'available',
    batch_number: 'AZ-500-B2',
    expiry_date: '2027-05-30',
    last_updated: '2026-08-13'
  },
  {
    id: 'inv-7',
    pharmacy_id: 'pharm-3',
    medicine_id: 'med-3',
    pharmacy_name: 'Wellness Forever Day & Night Chemists',
    medicine_name: 'Azithromycin 500mg',
    generic_name: 'Azithromycin',
    strength: '500 mg',
    form: 'Tablet',
    stock_quantity: 28,
    price: 12.90,
    status: 'available',
    batch_number: 'WF-AZ-99',
    expiry_date: '2027-06-20',
    last_updated: '2026-08-12'
  },
  {
    id: 'inv-8',
    pharmacy_id: 'pharm-1',
    medicine_id: 'med-4',
    pharmacy_name: 'Apollo 24|7 Pharmacy — Metro Heights',
    medicine_name: 'Amoxicillin + Clavulanic Acid 625mg',
    generic_name: 'Amoxicillin and Potassium Clavulanate (Augmentin)',
    strength: '625 mg',
    form: 'Tablet',
    stock_quantity: 4,
    price: 14.20,
    status: 'low_stock',
    batch_number: 'AUG-625-X',
    expiry_date: '2026-12-31',
    last_updated: '2026-08-14'
  },
  {
    id: 'inv-9',
    pharmacy_id: 'pharm-4',
    medicine_id: 'med-4',
    pharmacy_name: 'Fortis Healthway Pharmacy',
    medicine_name: 'Amoxicillin + Clavulanic Acid 625mg',
    generic_name: 'Amoxicillin and Potassium Clavulanate (Augmentin)',
    strength: '625 mg',
    form: 'Tablet',
    stock_quantity: 6,
    price: 14.80,
    status: 'low_stock',
    batch_number: 'FH-AUG-11',
    expiry_date: '2027-01-15',
    last_updated: '2026-08-10'
  },
  {
    id: 'inv-10',
    pharmacy_id: 'pharm-1',
    medicine_id: 'med-8',
    pharmacy_name: 'Apollo 24|7 Pharmacy — Metro Heights',
    medicine_name: 'Salbutamol Inhaler 100mcg',
    generic_name: 'Salbutamol (Albuterol) Inhaler',
    strength: '100 mcg (200 doses)',
    form: 'Inhaler',
    stock_quantity: 3,
    price: 10.90,
    status: 'low_stock',
    batch_number: 'AST-INH-02',
    expiry_date: '2027-04-10',
    last_updated: '2026-08-13'
  },
  {
    id: 'inv-11',
    pharmacy_id: 'pharm-2',
    medicine_id: 'med-12',
    pharmacy_name: 'MedPlus Health & Chemist',
    medicine_name: 'Losartan Potassium 50mg',
    generic_name: 'Losartan Potassium',
    strength: '50 mg',
    form: 'Tablet',
    stock_quantity: 0,
    price: 6.90,
    status: 'unavailable',
    batch_number: 'LOS-50-OUT',
    expiry_date: '2026-10-30',
    last_updated: '2026-08-08'
  },
  {
    id: 'inv-12',
    pharmacy_id: 'pharm-1',
    medicine_id: 'med-16',
    pharmacy_name: 'Apollo 24|7 Pharmacy — Metro Heights',
    medicine_name: 'Dolo 650',
    generic_name: 'Paracetamol 650mg',
    strength: '650 mg',
    form: 'Tablet',
    stock_quantity: 250,
    price: 3.70,
    status: 'available',
    batch_number: 'DOLO-650-AUG',
    expiry_date: '2028-03-31',
    last_updated: '2026-08-14'
  }
];

export const INITIAL_REMINDERS: Reminder[] = [
  {
    id: 'rem-1',
    user_id: 'usr-demo',
    medicine_name: 'Pantoprazole 40mg',
    dosage: '1 Tablet (40mg)',
    time: '07:30',
    frequency: 'Daily',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    start_date: '2026-08-01',
    notes: 'Take on empty stomach 30 mins before breakfast.',
    is_active: true,
    last_taken: '2026-08-14 07:32'
  },
  {
    id: 'rem-2',
    user_id: 'usr-demo',
    medicine_name: 'Metformin 500mg SR',
    dosage: '1 Tablet with lunch',
    time: '13:00',
    frequency: 'Daily',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    start_date: '2026-08-01',
    notes: 'Take during or immediately after meals.',
    is_active: true
  },
  {
    id: 'rem-3',
    user_id: 'usr-demo',
    medicine_name: 'Vitamin D3 60,000 IU',
    dosage: '1 Capsule',
    time: '20:00',
    frequency: 'Weekly',
    days: ['Sun'],
    start_date: '2026-08-03',
    end_date: '2026-09-28',
    notes: 'Take with warm milk on Sunday nights.',
    is_active: true
  }
];

export const SAMPLE_PRESCRIPTIONS = [
  {
    title: 'General Physician Rx (Fever & Cough)',
    doctor: 'Dr. Ramesh Sharma, M.D. (Internal Medicine)',
    clinic: 'City Care Polyclinic, Bengaluru',
    date: '14-Aug-2026',
    text: `Rx
1. Tab. Dolo 650 (Paracetamol 650mg) — 1 tab TDS x 3 days
2. Tab. Azithromycin 500mg — 1 tab OD before meals x 3 days
3. Tab. Montelukast 10mg + Levocetirizine 5mg — 1 tab HS x 5 days
4. Syp. Ascoril-D — 10ml TDS x 5 days
Adv: Drink warm fluids, steam inhalation twice daily.`
  },
  {
    title: 'Cardiology / Hypertension Follow-up Rx',
    doctor: 'Dr. Priya V. Nair, D.M. (Cardiology)',
    clinic: 'Apex Heart Centre, Koramangala',
    date: '10-Aug-2026',
    text: `Rx (Follow-up)
1. Tab. Amlodipine 5mg — 1 tab OD morning after breakfast
2. Tab. Atorvastatin 20mg — 1 tab HS after dinner
3. Tab. Pantoprazole 40mg — 1 tab OD before breakfast
Adv: Low sodium diet, 30 min daily brisk walking.`
  }
];
